import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Crear from "../components/buttons/create"

const Home: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>Tiendita</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          De remate 🔥
        </h1>
        <div>
          <Link
            className="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-green-400 to-blue-600 group-hover:from-green-400 group-hover:to-blue-600 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800"
            href="/producto"
          >
            <span className="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
              Ver productos disponibles
            </span>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
